### ISSUE TITLE
missing key binds

### ISSUE THREAD

**Issue by holomorph** [Unia/gcolor3#18]
It would be nice if there were keys for Quit (M-q) and changing between the Color Chooser and Saved Colors, as in gcolor2.

**Comment by Unia** [comment]
The ability to implement these shortcuts is here now. Before I go and add what I think are good keyboard shortcuts to switch between the stack pages, what would your preference be?

**Comment by holomorph** [comment]
Just looking at gtk3-demo it looks like TAB to change context and arrow keys works as a way to move around, so perhaps that should be available (if it isn't already). I don't have any preference, though

**Comment by Unia** [comment]
Apparantly I already implemented a keyboard shortcut a few months ago: use F9 to change stack pages.

Does that solve your issue?

**Comment by holomorph** [comment]
I can't build master:
```
make[3]: Entering directory '/tmp/makepkg/gcolor3-git/src/gcolor3/src'
  CC       gcolor3-main.o
  CC       gcolor3-gcolor3-window.o
  CC       gcolor3-gcolor3-application.o
  CC       gcolor3-gcolor3-resources.o
In file included from gcolor3-window.h:28:0,
                 from gcolor3-window.c:30:
gcolor3-application.h:51:1: error: function declaration isn’t a prototype [-Werror=strict-prototypes]
 Gcolor3Application *gcolor3_application_new ();
 ^
gcolor3-window.c:65:36: error: ISO C does not allow extra ‘;’ outside of a function [-Werror=pedantic]
        GTK_TYPE_APPLICATION_WINDOW);
                                    ^
In file included from main.c:31:0:
gcolor3-application.h:51:1: error: function declaration isn’t a prototype [-Werror=strict-prototypes]
 Gcolor3Application *gcolor3_application_new ();
 ^
main.c:45:65: error: ISO C forbids initialization between function pointer and ‘void *’ [-Werror=pedantic]
  { "version", 'v', G_OPTION_FLAG_NO_ARG, G_OPTION_ARG_CALLBACK, _print_version_and_exit, N_("Show the application's version"), NULL },
                                                                 ^
main.c:45:65: note: (near initialization for ‘options[0].arg_data’)
In file included from gcolor3-application.c:29:0:
gcolor3-application.h:51:1: error: function declaration isn’t a prototype [-Werror=strict-prototypes]
 Gcolor3Application *gcolor3_application_new ();
 ^
gcolor3-application.c:36:91: error: ISO C does not allow extra ‘;’ outside of a function [-Werror=pedantic]
 G_DEFINE_TYPE_WITH_PRIVATE (Gcolor3Application, gcolor3_application, GTK_TYPE_APPLICATION);
                                                                                           ^
cc1: all warnings being treated as errors
Makefile:486: recipe for target 'gcolor3-main.o' failed
make[3]: *** [gcolor3-main.o] Error 1
make[3]: *** Waiting for unfinished jobs....
cc1: all warnings being treated as errors
Makefile:500: recipe for target 'gcolor3-gcolor3-application.o' failed
make[3]: *** [gcolor3-gcolor3-application.o] Error 1
cc1: all warnings being treated as errors
Makefile:514: recipe for target 'gcolor3-gcolor3-window.o' failed
make[3]: *** [gcolor3-gcolor3-window.o] Error 1
make[3]: Leaving directory '/tmp/makepkg/gcolor3-git/src/gcolor3/src'
Makefile:363: recipe for target 'all' failed
make[2]: *** [all] Error 2
make[2]: Leaving directory '/tmp/makepkg/gcolor3-git/src/gcolor3/src'
Makefile:451: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/tmp/makepkg/gcolor3-git/src/gcolor3'
Makefile:383: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by Unia** [comment]
D'oh. Fixed it with a force push. I fixed a typo to actually apply `AM_CFLAGS` from [common.mk](https://github.com/Unia/gcolor3/blob/master/common.mk) but I tested it with a cached build. It should work now.

**Comment by holomorph** [comment]
Crashes ._.
```
Starting program: /usr/bin/gcolor3 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".

** (gcolor3:9240): WARNING **: Error opening file: No such file or directory. Exiting...

[New Thread 0x7fffed82e700 (LWP 9245)]

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff61dd2d9 in malloc_consolidate () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007ffff61dd2d9 in malloc_consolidate () from /usr/lib/libc.so.6
#1  0x00007ffff61de64d in _int_malloc () from /usr/lib/libc.so.6
#2  0x00007ffff61e1394 in calloc () from /usr/lib/libc.so.6
#3  0x00007ffff67745b2 in g_malloc0 () from /usr/lib/libglib-2.0.so.0
#4  0x00007ffff6a61f06 in g_type_class_ref () from /usr/lib/libgobject-2.0.so.0
#5  0x00007ffff6a61eb4 in g_type_class_ref () from /usr/lib/libgobject-2.0.so.0
#6  0x00007ffff6a4a87c in g_object_new_valist () from /usr/lib/libgobject-2.0.so.0
#7  0x00007ffff6a4a9e1 in g_object_new () from /usr/lib/libgobject-2.0.so.0
#8  0x0000000000405aea in gcolor3_window_new (application=<optimized out>) at gcolor3-window.c:482
#9  0x000000000040455c in gcolor3_application_activate (application=0x64c0f0) at gcolor3-application.c:171
#10 0x00007ffff6a43524 in ?? () from /usr/lib/libgobject-2.0.so.0
#11 0x00007ffff6a5cf97 in g_signal_emit_valist () from /usr/lib/libgobject-2.0.so.0
#12 0x00007ffff6a5d8ef in g_signal_emit () from /usr/lib/libgobject-2.0.so.0
#13 0x00007ffff6d2d1f6 in ?? () from /usr/lib/libgio-2.0.so.0
#14 0x00007ffff6d2d3e2 in g_application_run () from /usr/lib/libgio-2.0.so.0
#15 0x000000000040406f in main (argc=1, argv=0x7fffffffdfe8) at main.c:84
```

**Comment by Unia** [comment]
Should be fixed now.

**Comment by holomorph** [comment]
Yay! Well F9 is there--is a keybind to quit feasible?

**Comment by Unia** [comment]
Your window manager should provide a key binding to close applications. The advantage of using your wm for this is that it is the same key binding for all applications, across all toolkits.

Or is there a scenario that I'm missing?

**Comment by Unia** [comment]
I'm closing this issue. Feel free to reopen or create a new issue if I indeed did miss a scenario! :)
